FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*
    
WORKDIR /app

RUN pip install cryptography && \
    pip install pyinstaller

COPY ransonware_files_decrypt.py .

RUN pyinstaller --onefile ransonware_files_decrypt.py

CMD ["cp", "/app/dist/ransonware_files_decrypt", "/output/"]
